# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b09f9efbe0eb219d51dae1a2b6e7ba34"
name = "rule-based-shipping"
handle = "rule-based-shipping-1"
application_url = "https://laboratory-trio-mini-ja.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_shipping"

[auth]
redirect_urls = [
  "https://laboratory-trio-mini-ja.trycloudflare.com/auth/callback",
  "https://laboratory-trio-mini-ja.trycloudflare.com/auth/shopify/callback",
  "https://laboratory-trio-mini-ja.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
